server:
  port: ${PORT}

spring:
  application:
    name: grab-auth-service
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://34.126.64.253:5432/grabcar
    username: grabcar
    password: grabcarpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600}  # Default if missing
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:8600}  # Default if missing