server:
  port: 9000

spring:
  application:
    name: grab-auth-service
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    date-format: dd-MM-yyyy
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600}  # Default if missing
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:8600}  # Default if missing