apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: grab-api-gateway
  name: grab-car
  namespace: grab-car
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grab-auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grab-auth-service
    spec:
      containers:
        - image: ervincode/grabcar-auth-service:latest
          imagePullPolicy: IfNotPresent
          name: grabcar-auth-service
          ports:
            - containerPort: 9000
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_AUTH_SERVICE
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_DRIVER

---
#services
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grab-auth-service
  name: grab-auth-service
  namespace: grab-car
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: grab-auth-service
  sessionAffinity: None
  type: LoadBalancer